ALL = ~r"\s*" X ~r"\s*$"
X = "(" ` BAREVAR _ "/" _ CONCEPT (_ REL _ Y)* ` ")"
Y = X / NAMEDCONST / VAR / STR / NUM
VAR = BAREVAR ALIGNMENT?
BAREVAR = ~r"[a-z]+[0-9]*"
NAMEDCONST = ~r"[a-z]{2,}\b|[+-](?!\d)" ALIGNMENT?
STR = "\"" ~r"[^\"\s]([^\"\n\r]*[^\"\s])?" "\"" ALIGNMENT?
CONCEPT = ~r"[^ \n\t)(]*" ALIGNMENT?
REL = ~r":[A-Za-z<][A-Za-z0-9<>-]*" ALIGNMENT?
NUM = ~r"[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?([a-zA-Z]*)?(-[0-9]+)?" ALIGNMENT?
ALIGNMENT = "~" ~r"[A-Za-z0-9.,]+"
_ = ~r"([ \t]*[\n\r][ \t]*)|[ \t]+"
` = ~r"[ \t]*[\n\r]?[ \t]*"

